# Generated by Django 5.1.4 on 2025-01-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_generated_resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
